name: 'BrowserStack Env Setup'
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: 'browserstack/github-actions/setup-env@master'
        with:
            username: ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            build-name: 'BUILD_INFO'
            project-name: 'REPO_NAME'

