name: BrowserStack Tests

on:
  push:
    branches:
      - master  # Specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build your web application and start the server
      # Add your build steps here

      - name: Set up BrowserStack environment
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: browserstack-build-1
          project-name: BrowserStack Sample


      - name: Terminate BrowserStack Local tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          action: terminate